### ISSUE TITLE
Original LIGA implementation

### ISSUE THREAD

**Issue by ErikTromp** [llaisdy/liga#1]
FYI: Just found this (I know, late to the party). LIGA has been available for quite a while in its original form (as used in the papers). https://github.com/ErikTromp/LIGA

**Comment by llaisdy** [comment]
Dear Erik

Thanks for the alert, I've updated the README.

When I contacted you by email in April 2014, you said your implementation was "proprietary and hence not open-source".  Is that still the case?  The repo does not specify a license.

Best wishes

Ivan

**Comment by ErikTromp** [comment]
The license is Apache2 and can be used by anyone for anything. We've had it as our main language detection algorithm in https://github.com/UnderstandLingBV/Tuktu for quite a while - right here https://github.com/UnderstandLingBV/Tuktu/blob/master/modules/nlp/app/tuktu/nlp/processors/LanguageDetection.scala

So yes, feel free to use any of it, compare it to your implementation, fix bugs - just know that the version I linked to (especially the PHP one) was used in the paper originally.

**Comment by llaisdy** [comment]
Thanks.
